### ISSUE TITLE
The specific issue is a java.lang.ClassNotFoundException: net.minecraft.client.renderer.LevelRenderer.

### ISSUE THREAD

**Issue by NikProMine** [illucc/Kontraption#41] opened 2024-08-15 12:53 UTC
Describe the bug (from ChatGPT):

The error you're encountering during the Minecraft server startup is related to the Kontraption mod. The specific issue is a java.lang.ClassNotFoundException: net.minecraft.client.renderer.LevelRenderer. This means that the mod is trying to reference a class (LevelRenderer) that is part of the Minecraft client, but it's being executed on a server, which does not have this class available.

---------------------------------------------------------------------------------------------------------------------------------------------------
Logs:

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2024-08-15 15:42:24
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.5-universal.jar%23297!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.3.5-universal.jar%23297!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23103!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23103!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23103!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23103!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23103!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23103!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23103!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at com.mohistmc.MohistMCStart.main(MohistMCStart.java:112) [server.jar:1.20.1-825] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?] {}
-- MOD kontraption --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
		at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:64) ~[kfflang-4.11.0.jar%23379!/:4.11.0] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.3.5.jar%23293!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/LevelRenderer
		at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?] {re:mixin}
		at java.lang.Class.getConstructor0(Class.java:3754) ~[?:?] {re:mixin}
		at java.lang.Class.getConstructor(Class.java:2442) ~[?:?] {re:mixin}
		at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:75) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.lambda$getListenerListInternal$0(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:61) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.LockHelper.get(LockHelper.java:44) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:39) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:50) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:279) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:255) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:247) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:202) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:196) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:190) ~[eventbus-6.0.5.jar%23150!/:?] {}
		at net.illuc.kontraption.Kontraption.<init>(Kontraption.kt:121) ~[kontraption-0.0.2+82af737bfe.jar%23271!/:0.0.2+82af737bfe] {re:classloading}
		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
		at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:64) ~[kfflang-4.11.0.jar%23379!/:4.11.0] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.3.5.jar%23293!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

	Mod File: /home/container/mods/kontraption-0.0.2+82af737bfe.jar
	Failure message: Kontraption (kontraption) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 0.0.2
	Mod Issue URL: https://github.com/illucc/Kontraption/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.LevelRenderer
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?] {re:mixin}
	at java.lang.Class.getConstructor0(Class.java:3754) ~[?:?] {re:mixin}
	at java.lang.Class.getConstructor(Class.java:2442) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:75) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.lambda$getListenerListInternal$0(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:61) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.LockHelper.get(LockHelper.java:44) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:39) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:50) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:279) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:255) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:247) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:202) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:196) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:190) ~[eventbus-6.0.5.jar%23150!/:?] {}
	at net.illuc.kontraption.Kontraption.<init>(Kontraption.kt:121) ~[kontraption-0.0.2+82af737bfe.jar%23271!/:0.0.2+82af737bfe] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:64) ~[kfflang-4.11.0.jar%23379!/:4.11.0] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.3.5.jar%23293!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}
---------------------------------------------------------------------------------------------------------------------------------------------------
**Versions**
 - VS2 version: 120-2.3.0-beta.5
 - Mekanism version: 1.20.1-10.4.8.43

**Comment by NikProMine** [comment] 2024-08-15 13:03
As far as I understand, I was using Kontraption mod on a server where it did not find class java.lang.ClassNotFoundException: net.minecraft.client.renderer.LevelRenderer and stopped working.

**Comment by PriestOfFern** [comment] 2024-08-16 02:45
Don’t use chatGPT for log debugging, it’s not a proper debugging tool, nor can it even imitate one. At the very least don’t shove it into your issue report

**Comment by PriestOfFern** [comment] 2024-08-16 02:48
Either way, this is most likely a mohist issue. Hybrid server software tends to be made in hacky ways, leading to issues with a lot of mods. Mohist is one of the worst offenders in this respect, and isn’t compatible with even VS2, as far as I am aware

**Comment by NikProMine** [comment] 2024-08-16 09:10
> Either way, this is most likely a mohist issue. Hybrid server software tends to be made in hacky ways, leading to issues with a lot of mods. Mohist is one of the worst offenders in this respect, and isn’t compatible with even VS2, as far as I am aware

This is not a server or core issue. This is a mod issue. I used ChatGPT to verify that this is a mod issue. The error is caused by trying to load a class intended for the Minecraft client on a dedicated server. I understand that the Mohist core is not the best solution, but I don't know of a better solution at this point.

**Comment by t8rt0ts** [comment] 2024-08-16 14:26
Proof by chat gpt

**Comment by getItemFromBlock** [comment] 2024-08-16 14:28
ChatGPT moment

**Comment by getItemFromBlock** [comment] 2024-08-16 14:30
> > Either way, this is most likely a mohist issue. Hybrid server software tends to be made in hacky ways, leading to issues with a lot of mods. Mohist is one of the worst offenders in this respect, and isn’t compatible with even VS2, as far as I am aware
> 
> This is not a server or core issue. This is a mod issue. I used ChatGPT to verify that this is a mod issue. The error is caused by trying to load a class intended for the Minecraft client on a dedicated server. I understand that the Mohist core is not the best solution, but I don't know of a better solution at this point.

Please don't use ChatGPT for this kind of things, it does not know anything about VS
The problem here is as said earlier that you are using Mohist and that it is known to break things with VS
Don't try to use any other mod loaders than forge or fabric and it will work

**Comment by illucc** [comment] 2024-08-17 12:35
![image](https://github.com/user-attachments/assets/a3f7334d-d40b-4c22-9510-c0e5e794139d)

seems like a duplicate of #27

**Closed as completed by illucc** 2024-08-17 12:35 UTC
Labels: bug
